services:
  - type: web
    name: moviehub-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: moviehub-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://moviehub-frontend.vercel.app

databases:
  - name: moviehub-db
    databaseName: moviehub
    user: moviehub_user
    plan: free
